jwt.secret=${JWT_SECRET}

resilience4j.ratelimiter.instances.default.limit-for-period=20
resilience4j.ratelimiter.instances.default.limit-refresh-period=1s
resilience4j.ratelimiter.instances.default.timeout-duration=0s

logging.level.co.edu.elbosque=INFO
spring.elasticsearch.uris=http://localhost:9200
