spring.datasource.url=jdbc:postgresql://localhost:5432/elbosque_portafolio
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
rabbitmq.exchange.ordenes=ordenes.exchange
rabbitmq.queue.ejecutada=ordenes.ejecutada.portafolio.queue
rabbitmq.routing.key.ejecutada=ordenes.ejecutada

alpaca.api.key=${ALPACA_KEY}
alpaca.api.secret=${ALPACA_SECRET}
alpaca.base.url=https://paper-api.alpaca.markets

servicios.mercados.nombre=ms-mercados

spring.elasticsearch.uris=http://localhost:9200
logging.level.co.edu.elbosque=INFO
