spring.datasource.url=jdbc:postgresql://localhost:5432/elbosque_reportes
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.elasticsearch.uris=http://localhost:9200

servicios.ordenes.nombre=ms-ordenes
servicios.usuarios.nombre=ms-usuarios
servicios.portafolio.nombre=ms-portafolio

logging.level.co.edu.elbosque=INFO
